# Generated by Django 4.2.7 on 2025-09-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("total_events", models.IntegerField(default=0)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serialno", models.IntegerField()),
                ("version", models.IntegerField()),
                ("account_id", models.CharField(db_index=True, max_length=50)),
                ("instance_id", models.CharField(db_index=True, max_length=50)),
                ("srcaddr", models.GenericIPAddressField(db_index=True)),
                ("dstaddr", models.GenericIPAddressField(db_index=True)),
                ("srcport", models.IntegerField(db_index=True)),
                ("dstport", models.IntegerField(db_index=True)),
                ("protocol", models.IntegerField(db_index=True)),
                ("packets", models.IntegerField()),
                ("bytes", models.BigIntegerField()),
                ("starttime", models.IntegerField(db_index=True)),
                ("endtime", models.IntegerField(db_index=True)),
                ("action", models.CharField(db_index=True, max_length=10)),
                ("log_status", models.CharField(max_length=10)),
                ("source_file", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["srcaddr", "starttime"],
                        name="events_even_srcaddr_c64d20_idx",
                    ),
                    models.Index(
                        fields=["dstaddr", "starttime"],
                        name="events_even_dstaddr_bbfda3_idx",
                    ),
                    models.Index(
                        fields=["action", "starttime"],
                        name="events_even_action_920e38_idx",
                    ),
                    models.Index(
                        fields=["account_id", "starttime"],
                        name="events_even_account_ebb4a7_idx",
                    ),
                    models.Index(
                        fields=["starttime", "endtime"],
                        name="events_even_startti_c74f65_idx",
                    ),
                ],
            },
        ),
    ]
