version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: eventdb
      MYSQL_USER: eventuser
      MYSQL_PASSWORD: eventpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

  # Django Backend with MySQL
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - media_data:/app/media
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - DATABASE_URL=mysql://eventuser:eventpass@mysql:3306/eventdb
    depends_on:
      - mysql
    restart: unless-stopped

  # React Frontend
  frontend:
    build: ./frontend/event-search-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000/api
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mysql_data:
  media_data:
