version: '3.8'

services:
  # Django Backend with SQLite (fastest for this use case)
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - media_data:/app/media
      - sqlite_data:/app/db_data
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "manage.py", "check"]
      interval: 30s
      timeout: 10s
      retries: 3

  # React Frontend
  frontend:
    build: ./frontend/event-search-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000/api
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  media_data:     # For uploaded files
  sqlite_data:    # For SQLite database persistence
